<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="Rohans-MBP-2.attlocal.net" name="com.salesforce.qa.testcases.LoginPageTest" tests="6" failures="0" timestamp="2020-06-15T16:36:20 PDT" time="9.501" errors="1">
  <testcase name="setUp" time="9.501" classname="com.salesforce.qa.testcases.LoginPageTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.salesforce.qa.utilities.CommonUtilities.takeScreenshotAtEndOfTest(CommonUtilities.java:58)
at com.salesforce.qa.testcases.LoginPageTest.setUp(LoginPageTest.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:64)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:364)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:318)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setUp -->
  <system-out/>
  <testcase name="loginPageTitleTest" time="0.000" classname="com.salesforce.qa.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- loginPageTitleTest -->
  <system-out/>
  <testcase name="loginTest" time="0.000" classname="com.salesforce.qa.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- loginTest -->
  <system-out/>
  <testcase name="logintest_invalidCredentials" time="0.000" classname="com.salesforce.qa.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- logintest_invalidCredentials -->
  <system-out/>
  <testcase name="logintest_invalidCredentials" time="0.000" classname="com.salesforce.qa.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- logintest_invalidCredentials -->
  <system-out/>
  <testcase name="logintest_rememberMe" time="0.000" classname="com.salesforce.qa.testcases.LoginPageTest">
    <skipped/>
  </testcase> <!-- logintest_rememberMe -->
  <system-out/>
</testsuite> <!-- com.salesforce.qa.testcases.LoginPageTest -->
